### ISSUE TITLE
Check Balance Wallet Ui Displays Incorrect ㄜ Value

### ISSUE THREAD

**Issue by tstol002** [hacash/wallet1#1]
Here we can see that address http://block.hacash.org/address/1KfVAAgSkfDVfr3WLkcsqBcptKwm2ffYhB has ㄜ672,734,979:240

We can also see the correct balance in the green color text in the wallet UI: https://gyazo.com/0370d51987067860ad91b896c8955d34

However, as you can see below it is then displaying it as ㄜ672 when in fact is is ㄜ6.72

Here's another example with http://block.hacash.org/address/1DYY4ZRsWnhjcwwnE3dWgtiqe2mctDS2HF where it shows 3,427 HAC as just 3: https://gyazo.com/3433d66a5be653a6c801592c7ab033f3

**Comment by jojoin** [comment]
It's just a string display problem and I'll fix it right away.

thank you!
